name: Full Security Scan (Trivy + ClamAV + YARA)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Security-full-scan:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout source
        uses: actions/checkout@v4

      ##################################################
      # 1️⃣ Trivy – Quét secrets và mã độc cơ bản
      ##################################################
      - name: 🛡️ Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: 🔍 Trivy Secret Scan (Table format)
        run: |
          echo "🔐 Trivy Secret Scan Result" > trivy_output.log
          trivy fs . \
            --scanners secret \
            --exit-code 0 \
            --format table | tee -a trivy_output.log

      ##################################################
      # 2️⃣ ClamAV – Quét virus, trojan, worm
      ##################################################
      - name: 🦠 Install ClamAV
        run: |
          sudo apt-get update
          sudo apt-get install -y clamav clamav-daemon

      - name: 🔄 Update ClamAV DB
        run: |
          sudo systemctl stop clamav-freshclam || true
          sudo systemctl stop clamav-daemon || true
          sudo freshclam

      - name: 🧪 Run ClamAV Scan
        run: |
          echo "🦠 ClamAV Scan Result" > clamav_output.log
          clamscan -r --infected --no-summary . | tee -a clamav_output.log || true

      ##################################################
      # 3️⃣ YARA – Pattern nhận diện malware tinh vi
      ##################################################
      - name: 🔧 Install YARA
        run: |
          sudo apt-get install -y yara git

      - name: 🌐 Clone YARA-Rules full repo
        run: |
          git clone https://github.com/Yara-Rules/rules.git yara_rules

      - name: 🧬 Run YARA on all rules (with tagged report)
        run: |
          echo "🧬 YARA Scan Result" > yara_output.log
          find yara_rules -type f \( -name "*.yar" -o -name "*.yara" \) | while read rule; do
            echo "🔎 Scanning with rule: $rule" | tee -a yara_output.log
            yara -r "$rule" . 2>> yara_output.log | tee -a yara_output.log || true
          done

      ##################################################
      # 5️⃣ Tổng hợp kết quả (summary.log)
      ##################################################
      - name: 📝 Generate Summary Report
        run: |
          echo "🧾 Tổng hợp kết quả quét bảo mật" > summary.log
          echo "==============================" >> summary.log

          if grep -q "Secret detected" trivy_output.log; then
            echo "🔐 Trivy: ⚠️ Có thể chứa secrets cần kiểm tra thêm." >> summary.log
          else
            echo "🔐 Trivy: ✅ Không phát hiện secrets." >> summary.log
          fi

          if grep -q "FOUND" clamav_output.log; then
            echo "🦠 ClamAV: ⚠️ Phát hiện mã độc nghi vấn (FOUND)." >> summary.log
          else
            echo "🦠 ClamAV: ✅ Không phát hiện mã độc." >> summary.log
          fi

          yara_matches=$(grep -v "^🔎 " yara_output.log | grep -v "^🧬" | grep -v "^warning" | grep -v "^$" | wc -l)
          if [ "$yara_matches" -gt 0 ]; then
            echo "🧬 YARA: ⚠️ Có $yara_matches rule match – cần kiểm tra thêm!" >> summary.log
          else
            echo "🧬 YARA: ✅ Không phát hiện mẫu độc hại." >> summary.log
          fi

      ##################################################
      # 5️⃣ Upload toàn bộ log + summary
      ##################################################
      - name: 📎 Upload full scan logs + summary
        uses: actions/upload-artifact@v4
        with:
          name: full-scan-logs
          path: |
            trivy_output.log
            clamav_output.log
            yara_output.log
            summary.logname: Full Security Scan (Trivy + ClamAV + YARA)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Security-full-scan:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout source
        uses: actions/checkout@v4

      ##################################################
      # 1️⃣ Trivy – Quét secrets và mã độc cơ bản
      ##################################################
      - name: 🛡️ Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: 🔍 Trivy Secret Scan (Table format)
        run: |
          echo "🔐 Trivy Secret Scan Result" > trivy_output.log
          trivy fs . \
            --scanners secret \
            --exit-code 0 \
            --format table | tee -a trivy_output.log

      ##################################################
      # 2️⃣ ClamAV – Quét virus, trojan, worm
      ##################################################
      - name: 🦠 Install ClamAV
        run: |
          sudo apt-get update
          sudo apt-get install -y clamav clamav-daemon

      - name: 🔄 Update ClamAV DB
        run: |
          sudo systemctl stop clamav-freshclam || true
          sudo systemctl stop clamav-daemon || true
          sudo freshclam

      - name: 🧪 Run ClamAV Scan
        run: |
          echo "🦠 ClamAV Scan Result" > clamav_output.log
          clamscan -r --infected --no-summary . | tee -a clamav_output.log || true

      ##################################################
      # 3️⃣ YARA – Pattern nhận diện malware tinh vi
      ##################################################
      - name: 🔧 Install YARA
        run: |
          sudo apt-get install -y yara git

      - name: 🌐 Clone YARA-Rules full repo
        run: |
          git clone https://github.com/Yara-Rules/rules.git yara_rules

      - name: 🧬 Run YARA on all rules (with tagged report)
        run: |
          echo "🧬 YARA Scan Result" > yara_output.log
          find yara_rules -type f \( -name "*.yar" -o -name "*.yara" \) | while read rule; do
            echo "🔎 Scanning with rule: $rule" | tee -a yara_output.log
            yara -r "$rule" . 2>> yara_output.log | tee -a yara_output.log || true
          done

      ##################################################
      # 5️⃣ Tổng hợp kết quả (summary.log)
      ##################################################
      - name: 📝 Generate Summary Report
        run: |
          echo "🧾 Tổng hợp kết quả quét bảo mật" > summary.log
          echo "==============================" >> summary.log

          if grep -q "Secret detected" trivy_output.log; then
            echo "🔐 Trivy: ⚠️ Có thể chứa secrets cần kiểm tra thêm." >> summary.log
          else
            echo "🔐 Trivy: ✅ Không phát hiện secrets." >> summary.log
          fi

          if grep -q "FOUND" clamav_output.log; then
            echo "🦠 ClamAV: ⚠️ Phát hiện mã độc nghi vấn (FOUND)." >> summary.log
          else
            echo "🦠 ClamAV: ✅ Không phát hiện mã độc." >> summary.log
          fi

          yara_matches=$(grep -v "^🔎 " yara_output.log | grep -v "^🧬" | grep -v "^warning" | grep -v "^$" | wc -l)
          if [ "$yara_matches" -gt 0 ]; then
            echo "🧬 YARA: ⚠️ Có $yara_matches rule match – cần kiểm tra thêm!" >> summary.log
          else
            echo "🧬 YARA: ✅ Không phát hiện mẫu độc hại." >> summary.log
          fi

      ##################################################
      # 5️⃣ Upload toàn bộ log + summary
      ##################################################
      - name: 📎 Upload full scan logs + summary
        uses: actions/upload-artifact@v4
        with:
          name: full-scan-logs
          path: |
            trivy_output.log
            clamav_output.log
            yara_output.log
            summary.logname: Full Security Scan (Trivy + ClamAV + YARA)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Security-full-scan:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout source
        uses: actions/checkout@v4

      ##################################################
      # 1️⃣ Trivy – Quét secrets và mã độc cơ bản
      ##################################################
      - name: 🛡️ Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: 🔍 Trivy Secret Scan (Table format)
        run: |
          echo "🔐 Trivy Secret Scan Result" > trivy_output.log
          trivy fs . \
            --scanners secret \
            --exit-code 0 \
            --format table | tee -a trivy_output.log

      ##################################################
      # 2️⃣ ClamAV – Quét virus, trojan, worm
      ##################################################
      - name: 🦠 Install ClamAV
        run: |
          sudo apt-get update
          sudo apt-get install -y clamav clamav-daemon

      - name: 🔄 Update ClamAV DB
        run: |
          sudo systemctl stop clamav-freshclam || true
          sudo systemctl stop clamav-daemon || true
          sudo freshclam

      - name: 🧪 Run ClamAV Scan
        run: |
          echo "🦠 ClamAV Scan Result" > clamav_output.log
          clamscan -r --infected --no-summary . | tee -a clamav_output.log || true

      ##################################################
      # 3️⃣ YARA – Pattern nhận diện malware tinh vi
      ##################################################
      - name: 🔧 Install YARA
        run: |
          sudo apt-get install -y yara git

      - name: 🌐 Clone YARA-Rules full repo
        run: |
          git clone https://github.com/Yara-Rules/rules.git yara_rules

      - name: 🧬 Run YARA on all rules (with tagged report)
        run: |
          echo "🧬 YARA Scan Result" > yara_output.log
          find yara_rules -type f \( -name "*.yar" -o -name "*.yara" \) | while read rule; do
            echo "🔎 Scanning with rule: $rule" | tee -a yara_output.log
            yara -r "$rule" . 2>> yara_output.log | tee -a yara_output.log || true
          done

      ##################################################
      # 5️⃣ Tổng hợp kết quả (summary.log)
      ##################################################
      - name: 📝 Generate Summary Report
        run: |
          echo "🧾 Tổng hợp kết quả quét bảo mật" > summary.log
          echo "==============================" >> summary.log

          if grep -q "Secret detected" trivy_output.log; then
            echo "🔐 Trivy: ⚠️ Có thể chứa secrets cần kiểm tra thêm." >> summary.log
          else
            echo "🔐 Trivy: ✅ Không phát hiện secrets." >> summary.log
          fi

          if grep -q "FOUND" clamav_output.log; then
            echo "🦠 ClamAV: ⚠️ Phát hiện mã độc nghi vấn (FOUND)." >> summary.log
          else
            echo "🦠 ClamAV: ✅ Không phát hiện mã độc." >> summary.log
          fi

          yara_matches=$(grep -v "^🔎 " yara_output.log | grep -v "^🧬" | grep -v "^warning" | grep -v "^$" | wc -l)
          if [ "$yara_matches" -gt 0 ]; then
            echo "🧬 YARA: ⚠️ Có $yara_matches rule match – cần kiểm tra thêm!" >> summary.log
          else
            echo "🧬 YARA: ✅ Không phát hiện mẫu độc hại." >> summary.log
          fi

      ##################################################
      # 5️⃣ Upload toàn bộ log + summary
      ##################################################
      - name: 📎 Upload full scan logs + summary
        uses: actions/upload-artifact@v4
        with:
          name: full-scan-logs
          path: |
            trivy_output.log
            clamav_output.log
            yara_output.log
            summary.logname: Full Security Scan (Trivy + ClamAV + YARA)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Security-full-scan:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout source
        uses: actions/checkout@v4

      ##################################################
      # 1️⃣ Trivy – Quét secrets và mã độc cơ bản
      ##################################################
      - name: 🛡️ Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: 🔍 Trivy Secret Scan (Table format)
        run: |
          echo "🔐 Trivy Secret Scan Result" > trivy_output.log
          trivy fs . \
            --scanners secret \
            --exit-code 0 \
            --format table | tee -a trivy_output.log

      ##################################################
      # 2️⃣ ClamAV – Quét virus, trojan, worm
      ##################################################
      - name: 🦠 Install ClamAV
        run: |
          sudo apt-get update
          sudo apt-get install -y clamav clamav-daemon

      - name: 🔄 Update ClamAV DB
        run: |
          sudo systemctl stop clamav-freshclam || true
          sudo systemctl stop clamav-daemon || true
          sudo freshclam

      - name: 🧪 Run ClamAV Scan
        run: |
          echo "🦠 ClamAV Scan Result" > clamav_output.log
          clamscan -r --infected --no-summary . | tee -a clamav_output.log || true

      ##################################################
      # 3️⃣ YARA – Pattern nhận diện malware tinh vi
      ##################################################
      - name: 🔧 Install YARA
        run: |
          sudo apt-get install -y yara git

      - name: 🌐 Clone YARA-Rules full repo
        run: |
          git clone https://github.com/Yara-Rules/rules.git yara_rules

      - name: 🧬 Run YARA on all rules (with tagged report)
        run: |
          echo "🧬 YARA Scan Result" > yara_output.log
          find yara_rules -type f \( -name "*.yar" -o -name "*.yara" \) | while read rule; do
            echo "🔎 Scanning with rule: $rule" | tee -a yara_output.log
            yara -r "$rule" . 2>> yara_output.log | tee -a yara_output.log || true
          done

      ##################################################
      # 5️⃣ Tổng hợp kết quả (summary.log)
      ##################################################
      - name: 📝 Generate Summary Report
        run: |
          echo "🧾 Tổng hợp kết quả quét bảo mật" > summary.log
          echo "==============================" >> summary.log

          if grep -q "Secret detected" trivy_output.log; then
            echo "🔐 Trivy: ⚠️ Có thể chứa secrets cần kiểm tra thêm." >> summary.log
          else
            echo "🔐 Trivy: ✅ Không phát hiện secrets." >> summary.log
          fi

          if grep -q "FOUND" clamav_output.log; then
            echo "🦠 ClamAV: ⚠️ Phát hiện mã độc nghi vấn (FOUND)." >> summary.log
          else
            echo "🦠 ClamAV: ✅ Không phát hiện mã độc." >> summary.log
          fi

          yara_matches=$(grep -v "^🔎 " yara_output.log | grep -v "^🧬" | grep -v "^warning" | grep -v "^$" | wc -l)
          if [ "$yara_matches" -gt 0 ]; then
            echo "🧬 YARA: ⚠️ Có $yara_matches rule match – cần kiểm tra thêm!" >> summary.log
          else
            echo "🧬 YARA: ✅ Không phát hiện mẫu độc hại." >> summary.log
          fi

      ##################################################
      # 5️⃣ Upload toàn bộ log + summary
      ##################################################
      - name: 📎 Upload full scan logs + summary
        uses: actions/upload-artifact@v4
        with:
          name: full-scan-logs
          path: |
            trivy_output.log
            clamav_output.log
            yara_output.log
            summary.log
